### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by JoshuaMorris** [iamJoeTaylor/vanilla-autofill-event#1]
Found in Google Chrome Version 49.0.2566.0 canary (64-bit) 
autofill-event.js:28 Uncaught TypeError: Cannot read property 'querySelectorAll' of null

**Comment by nl0** [comment]
bump.
`findParentForm()` may return `null`, so we should check for `null` when trying to invoke the `querySelectorAll` method

**Comment by pimhooghiemstra** [comment]
I stumbled on this also today. The fix of @nl0 works for me, I added the following in my local copy of the lib

`addGlobalEventListener('blur', function(target) {
    // setTimeout needed for Chrome as it fills other
    // form fields a little later...
    window.setTimeout(function() {
      if (findParentForm(target) !== null) {
        window.checkAndTriggerAutoFillEvent(findParentForm(target).querySelectorAll('input'));
      }
    }, 20);
  });`

**Comment by iamJoeTaylor** [comment]
I'm sorry everyone here I've been terribly busy getting married I didn't mean to ignore.

Working on this now. Expect resolution today.

**Comment by JoshuaMorris** [comment]
Thanks for considering the PR. Just wanted to help. 

Congrats on getting married!

**Comment by nl0** [comment]
@iamJoeTaylor 👍 and 🎉
